services:
  config-service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      # Access http://localhost/
      - 8088:8088

    environment:
      SPRING_PROFILES_ACTIVE: docker
