server:
  port: 8088

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stockgit/m1_config_service.git
          clone-on-start: true
        bootstrap: true
      enabled: true

  application:
    name: config-server

  profiles:
    active: native
  output:
    ansi:
      enabled: always

#:
#  pattern:
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

javamelody:
  # Initialization parameters for JavaMelody
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests
    log: true

    # to exclude images, css, fonts and js urls from the monitoring:
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)

    # to add basic auth:
    authorized-users: admin:1234

    # to change the default storage directory:
    storage-directory: /tmp/javamelody

    # to change the default "/monitoring" path
    monitoring-path: /admin/performance